project:
  type: book

book:
  title: "Autism All Grown Up"
  author: "Ariel Balter"
  chapters:
    - index.qmd
    - executive_summary.qmd
    - autism_2024.qmd
    - the_lost_generations.qmd
    - oregon.qmd
    - autism_all_grown_up.qmd
    - funding.qmd
    - budget.qmd
  appendices:
    - glossary.qmd
    - representitive_salaries.qmd
    - potential_funders.qmd
    - neurodiversity_and_neurodivergence.qmd


format:
  html:
    theme: litera
    output-dir: docs
  pdf:
    documentclass: scrreprt

editor: visual
